/**
  ******************************************************************************
  * @file    Display/LTDC_PicturesFromSDCard/Inc/main.h 
  * @author  MCD Application Team
  * @brief   Header for main.c module
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2016 STMicroelectronics International N.V. 
  * All rights reserved.</center></h2>
  *
  * Redistribution and use in source and binary forms, with or without 
  * modification, are permitted, provided that the following conditions are met:
  *
  * 1. Redistribution of source code must retain the above copyright notice, 
  *    this list of conditions and the following disclaimer.
  * 2. Redistributions in binary form must reproduce the above copyright notice,
  *    this list of conditions and the following disclaimer in the documentation
  *    and/or other materials provided with the distribution.
  * 3. Neither the name of STMicroelectronics nor the names of other 
  *    contributors to this software may be used to endorse or promote products 
  *    derived from this software without specific written permission.
  * 4. This software, including modifications and/or derivative works of this 
  *    software, must execute solely and exclusively on microcontroller or
  *    microprocessor devices manufactured by or for STMicroelectronics.
  * 5. Redistribution and use of this software other than as permitted under 
  *    this license is void and will automatically terminate your rights under 
  *    this license. 
  *
  * THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" 
  * AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT 
  * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
  * PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY
  * RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT 
  * SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
  * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
  * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
  * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
  * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
  * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  *
  ******************************************************************************
  */
  
/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

/* Includes ------------------------------------------------------------------*/

//#define UART_CNT 10
#define UART_Q_BUFF_SIZE	2048
#define CAN_Q_BUFF_SIZE 	512

#define UART_PC	  0
#define UART_485  1
#define UART_HCPU 2


#include "stm32746g_discovery.h"
#include "stm32746g_discovery_lcd.h"
#include <stdlib.h>
#include "fatfs_storage.h"
#include "lcd_log.h"

/* FatFs includes component */





#include "ff_gen_drv.h"
#include "sd_diskio.h"

#include "gm_hal_protocol.h"
#include "gm_hal_uart.h"
#include "gm_hal_crc16.h"

#include "proc_booting.h"
#include "gm_hal_util.h"
#include "gm_hal_speaker.h"


#include "proc_can_tx.h"
#include "proc_can_rx.h"
#include "proc_uart_rx.h"
#include "proc_uart_tx.h"
#include "proc_motion.h"
#include "proc_pc_edit.h"
#include "proc_sdcard.h"
#include "proc_make_packet.h"
#include "proc_ac_init.h"
#include "proc_led.h"
	
	  
	  
#include "app_can_protocol_case.h"
#include "app_can_protocol.h"
#include "app_uart_protocol_case.h"
#include "app_uart_protocol.h"
#include "app_util.h"
#include "app_key_position.h"
#include "app_rng_random.h"
#include "app_uninstall.h"

	  
#include "dl_can.h"
//#include "gm_hal_make_tx_protocol.h"
#include "net_phd_pid.h"


#define ARDUINO_RX_D0_Pin GPIO_PIN_7
#define ARDUINO_RX_D0_GPIO_Port GPIOC	  
#define ARDUINO_TX_D1_Pin GPIO_PIN_6
#define ARDUINO_TX_D1_GPIO_Port GPIOC
	  
uint32_t Elapsed(uint32_t time);
uint32_t GetElapsed(uint32_t time1, uint32_t time2);
uint32_t GetTickCount(void);

uint32_t Elapsed_motion(uint32_t time);
uint32_t GetTickCount_motion(void);
void TickCountReset_motion(void);




extern SD_HandleTypeDef uSdHandle;
extern CAN_HandleTypeDef CanHandle;

extern DMA_HandleTypeDef hdma_uart7_tx;
extern DMA_HandleTypeDef hdma_usart1_tx;
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart7;
extern UART_HandleTypeDef huart6;

extern uint8_t flag_ac_init_secse;

extern uint32_t *mt_all_addr;
extern uint32_t *mt_rep_addr;




#define MOTION_RESET_CNT 5

#define RS485_DE_PIN GPIO_PIN_8
#define RS485_DE_PORT GPIOF

#define MOTION_SDRAM_START_ADDRESS	0xC0020000
#define MOTION_SDRAM_END_ADDRESS	0xC07FFFFF
#define	MOTION_SDRAM_PAGE_SIZE		0xFFFF		//65,535Byte
#define	MOTION_SDRAM_SECTOR_SIZE	0xFFFFF   // 1,048,575Byte

#define MOTION_DATA_BYTE	8

#define	MOTION_SDRAM_SECTOR1_PAGE1_START_ADDRESS	MOTION_SDRAM_START_ADDRESS   // 0xC002 0000
#define	MOTION_SDRAM_SECTOR1_PAGE1_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE1_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))   // 0xC002 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE2_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE1_END_ADDRESS+1)	// 0xC003 0000
#define MOTION_SDRAM_SECTOR1_PAGE2_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE2_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC003 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE3_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE2_END_ADDRESS+1)	// 0xC004 0000
#define MOTION_SDRAM_SECTOR1_PAGE3_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE3_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC004 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE4_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE3_END_ADDRESS+1)	// 0xC005 0000
#define MOTION_SDRAM_SECTOR1_PAGE4_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE4_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC005 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE5_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE4_END_ADDRESS+1)	// 0xC006 0000
#define MOTION_SDRAM_SECTOR1_PAGE5_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE5_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC006 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE6_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE5_END_ADDRESS+1)	// 0xC007 0000
#define MOTION_SDRAM_SECTOR1_PAGE6_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE6_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC007 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE7_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE6_END_ADDRESS+1)	// 0xC008 0000
#define MOTION_SDRAM_SECTOR1_PAGE7_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE7_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC008 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE8_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE7_END_ADDRESS+1)	// 0xC009 0000
#define MOTION_SDRAM_SECTOR1_PAGE8_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE8_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC009 FFFF

#define MOTION_SDRAM_SECTOR1_PAGE9_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE8_END_ADDRESS+1)	// 0xC00A 0000
#define MOTION_SDRAM_SECTOR1_PAGE9_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE9_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC00A FFFF

#define MOTION_SDRAM_SECTOR1_PAGE10_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE9_END_ADDRESS+1)	// 0xC00B 0000
#define MOTION_SDRAM_SECTOR1_PAGE10_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE10_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC00B FFFF

#define MOTION_SDRAM_SECTOR1_PAGE11_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE10_END_ADDRESS+1)	// 0xC00C 0000
#define MOTION_SDRAM_SECTOR1_PAGE11_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE11_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC00C FFFF

#define MOTION_SDRAM_SECTOR1_PAGE12_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE11_END_ADDRESS+1)	// 0xC00D 0000
#define MOTION_SDRAM_SECTOR1_PAGE12_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE12_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC00D FFFF

#define MOTION_SDRAM_SECTOR1_PAGE13_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE12_END_ADDRESS+1)	// 0xC00E 0000
#define MOTION_SDRAM_SECTOR1_PAGE13_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE13_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC00E FFFF

#define MOTION_SDRAM_SECTOR1_PAGE14_START_ADDRESS	(MOTION_SDRAM_SECTOR1_PAGE13_END_ADDRESS+1)	// 0xC00F 0000
#define MOTION_SDRAM_SECTOR1_PAGE14_END_ADDRESS		(MOTION_SDRAM_SECTOR1_PAGE14_START_ADDRESS + (MOTION_SDRAM_PAGE_SIZE))		// 0xC00F FFFF


#define	MOTION_SDRAM_SECTOR1_START_ADDRESS	MOTION_SDRAM_START_ADDRESS   // 0xC002 0000
#define	MOTION_SDRAM_SECTOR1_END_ADDRESS	(MOTION_SDRAM_SECTOR1_START_ADDRESS+MOTION_SDRAM_SECTOR_SIZE)   // 0xC011 FFFF

#define MOTION_SDRAM_SECTOR1_END_CNT		(MOTION_SDRAM_SECTOR_SIZE / MOTION_DATA_BYTE)

#define	MOTION_SDRAM_SECTOR2_START_ADDRESS	(MOTION_SDRAM_SECTOR1_END_ADDRESS+1)   // 0xC012 0000
#define	MOTION_SDRAM_SECTOR2_END_ADDRESS	(MOTION_SDRAM_SECTOR2_START_ADDRESS+MOTION_SDRAM_SECTOR_SIZE)   // 0xC021 FFFF

#define MOTION_SDRAM_SECTOR2_END_CNT		((MOTION_SDRAM_SECTOR_SIZE * 2) / MOTION_DATA_BYTE)

#define	MOTION_SDRAM_SECTOR3_START_ADDRESS	(MOTION_SDRAM_SECTOR2_END_ADDRESS+1)   // 0xC022 0000
#define	MOTION_SDRAM_SECTOR3_END_ADDRESS	(MOTION_SDRAM_SECTOR3_START_ADDRESS+MOTION_SDRAM_SECTOR_SIZE)   // 0xC031 FFFF

#define MOTION_SDRAM_SECTOR3_END_CNT		((MOTION_SDRAM_SECTOR_SIZE * 3) / MOTION_DATA_BYTE)

#define	MOTION_SDRAM_SECTOR4_START_ADDRESS	(MOTION_SDRAM_SECTOR3_END_ADDRESS+1)   // 0xC032 0000
#define	MOTION_SDRAM_SECTOR4_END_ADDRESS	(MOTION_SDRAM_SECTOR4_START_ADDRESS+MOTION_SDRAM_SECTOR_SIZE)   // 0xC41 FFFF

#define MOTION_SDRAM_SECTOR4_END_CNT		((MOTION_SDRAM_SECTOR_SIZE * 4) / MOTION_DATA_BYTE)

#if 0
#define MOTION_SDRAM_SECTOR5_PAGE_END_CNT		(MOTION_SDRAM_PAGE_SIZE / MOTION_DATA_BYTE)

#define	MOTION_SDRAM_SECTOR5_PAGE1_START_ADDRESS	(MOTION_SDRAM_SECTOR4_END_ADDRESS+1)   // 0xC042 0000
#define	MOTION_SDRAM_SECTOR5_PAGE1_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE1_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC042 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE2_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE1_END_ADDRESS+1)   // 0xC043 0000
#define	MOTION_SDRAM_SECTOR5_PAGE2_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE2_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC043 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE3_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE2_END_ADDRESS+1)   // 0xC044 0000
#define	MOTION_SDRAM_SECTOR5_PAGE3_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE3_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC044 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE4_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE3_END_ADDRESS+1)   // 0xC045 0000
#define	MOTION_SDRAM_SECTOR5_PAGE4_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE4_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC045 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE5_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE4_END_ADDRESS+1)   // 0xC046 0000
#define	MOTION_SDRAM_SECTOR5_PAGE5_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE5_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC046 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE6_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE5_END_ADDRESS+1)   // 0xC047 0000
#define	MOTION_SDRAM_SECTOR5_PAGE6_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE6_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC047 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE7_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE6_END_ADDRESS+1)   // 0xC048 0000
#define	MOTION_SDRAM_SECTOR5_PAGE7_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE7_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC048 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE8_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE7_END_ADDRESS+1)   // 0xC049 0000
#define	MOTION_SDRAM_SECTOR5_PAGE8_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE8_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC049 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE9_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE8_END_ADDRESS+1)   // 0xC04A 0000
#define	MOTION_SDRAM_SECTOR5_PAGE9_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE9_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC04A FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE10_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE9_END_ADDRESS+1)   // 0xC04B 0000
#define	MOTION_SDRAM_SECTOR5_PAGE10_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE10_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC04B FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE11_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE10_END_ADDRESS+1)   // 0xC04C 0000
#define	MOTION_SDRAM_SECTOR5_PAGE11_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE11_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC04C FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE12_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE11_END_ADDRESS+1)   // 0xC04D 0000
#define	MOTION_SDRAM_SECTOR5_PAGE12_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE12_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC04D FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE13_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE12_END_ADDRESS+1)   // 0xC04E 0000
#define	MOTION_SDRAM_SECTOR5_PAGE13_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE13_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC04E FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE14_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE13_END_ADDRESS+1)   // 0xC04F 0000
#define	MOTION_SDRAM_SECTOR5_PAGE14_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE14_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC04F FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE15_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE14_END_ADDRESS+1)   // 0xC050 0000
#define	MOTION_SDRAM_SECTOR5_PAGE15_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE15_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC050 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE16_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE15_END_ADDRESS+1)   // 0xC051 0000
#define	MOTION_SDRAM_SECTOR5_PAGE16_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE16_START_ADDRESS+MOTION_SDRAM_PAGE_SIZE)   // 0xC051 FFFF

#else

#define MOTION_SDRAM_SECTOR5_PAGE2_END_CNT		((MOTION_SDRAM_PAGE_SIZE*2) / MOTION_DATA_BYTE)

#define	MOTION_SDRAM_SECTOR5_PAGE1_2_START_ADDRESS		(MOTION_SDRAM_SECTOR4_END_ADDRESS+1)   // 0xC042 0000
#define	MOTION_SDRAM_SECTOR5_PAGE1_2_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE1_2_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC042 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE3_4_START_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE1_2_END_ADDRESS+1)   // 0xC043 0000
#define	MOTION_SDRAM_SECTOR5_PAGE3_4_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE3_4_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC043 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE5_6_START_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE3_4_END_ADDRESS+1)   // 0xC044 0000
#define	MOTION_SDRAM_SECTOR5_PAGE5_6_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE5_6_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC044 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE7_8_START_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE5_6_END_ADDRESS+1)   // 0xC045 0000
#define	MOTION_SDRAM_SECTOR5_PAGE7_8_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE7_8_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC045 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE9_10_START_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE7_8_END_ADDRESS+1)   // 0xC045 0000
#define	MOTION_SDRAM_SECTOR5_PAGE9_10_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE9_10_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC045 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE11_12_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE9_10_END_ADDRESS+1)   // 0xC045 0000
#define	MOTION_SDRAM_SECTOR5_PAGE11_12_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE11_12_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC045 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE13_14_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE11_12_END_ADDRESS+1)   // 0xC045 0000
#define	MOTION_SDRAM_SECTOR5_PAGE13_14_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE13_14_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC045 FFFF

#define	MOTION_SDRAM_SECTOR5_PAGE15_16_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE13_14_END_ADDRESS+1)   // 0xC045 0000
#define	MOTION_SDRAM_SECTOR5_PAGE15_16_END_ADDRESS		(MOTION_SDRAM_SECTOR5_PAGE15_16_START_ADDRESS+(MOTION_SDRAM_PAGE_SIZE*2) + 1)   // 0xC045 FFFF\


#define	MOTION_SDRAM_SECTOR6_START_ADDRESS	(MOTION_SDRAM_SECTOR5_PAGE15_16_END_ADDRESS+1)   // 0xC045 0000

#endif

/*
__packed typedef struct{
	uint32_t cnt;
	p_data_save_t data[1000];
}test_sds_t;
extern test_sds_t *test_sds;
*/
/*
__packed typedef struct{
	p_data_save_t ddatqa[1000];
}ppp_data_save_t;

extern ppp_data_save_t *ppp_ad;
*/
//extern data_save_t *p_data_save_motion;
	  
/* Exported types ------------------------------------------------------------*/
/* Exported constants --------------------------------------------------------*/
/* Exported macro ------------------------------------------------------------*/
/* Exported functions ------------------------------------------------------- */

#endif /* __MAIN_H */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
