#ifndef _GM_HAL_PROTOCOL1_5_PID_EDIT_H_
#define _GM_HAL_PROTOCOL1_5_PID_EDIT_H_
#pragma pack(1)
/***********************************************************EDIT_SUB_PID_ACTION**********************************************************/


///////////////////////////action///////////////////////////
#define	EDIT_ACTION_REC_START							0
#define	EDIT_ACTION_REC_END								1
#define	EDIT_ACTION_PLAY_START							2
#define	EDIT_ACTION_PLAY_END							3
#define	EDIT_ACTION_REPEAT_PLAY_START					4
#define	EDIT_ACTION_REPEAT_PLAY_END						5
#define	EDIT_ACTION_MOTION1_REC_START					6
#define	EDIT_ACTION_MOTION1_REC_END						7
#define	EDIT_ACTION_MOTION2_REC_START					8
#define	EDIT_ACTION_MOTION2_REC_END						9
#define	EDIT_ACTION_MOTION3_REC_START					10
#define	EDIT_ACTION_MOTION3_REC_END						11
#define	EDIT_ACTION_MOTION4_REC_START					12
#define	EDIT_ACTION_MOTION4_REC_END						13
#define	EDIT_ACTION_MOTION5_REC_START					14
#define	EDIT_ACTION_MOTION5_REC_END						15
#define	EDIT_ACTION_MOTION6_REC_START					16
#define	EDIT_ACTION_MOTION6_REC_END						17
#define	EDIT_ACTION_MOTION7_REC_START					18
#define	EDIT_ACTION_MOTION7_REC_END						19
#define	EDIT_ACTION_MOTION8_REC_START					20
#define	EDIT_ACTION_MOTION8_REC_END						21
#define	EDIT_ACTION_MOTION1_PLAY_START					22
#define	EDIT_ACTION_MOTION1_PLAY_END					23
#define	EDIT_ACTION_MOTION2_PLAY_START					24
#define	EDIT_ACTION_MOTION2_PLAY_END					25
#define	EDIT_ACTION_MOTION3_PLAY_START					26
#define	EDIT_ACTION_MOTION3_PLAY_END					27
#define	EDIT_ACTION_MOTION4_PLAY_START					28
#define	EDIT_ACTION_MOTION4_PLAY_END					29
#define	EDIT_ACTION_MOTION5_PLAY_START					30
#define	EDIT_ACTION_MOTION5_PLAY_END					31
#define	EDIT_ACTION_MOTION6_PLAY_START					32
#define	EDIT_ACTION_MOTION6_PLAY_END					33
#define	EDIT_ACTION_MOTION7_PLAY_START					34
#define	EDIT_ACTION_MOTION7_PLAY_END					35
#define	EDIT_ACTION_MOTION8_PLAY_START					36
#define	EDIT_ACTION_MOTION8_PLAY_END					37
#define	EDIT_ACTION_PLAY_AND_REC_START					38
#define	EDIT_ACTION_PLAY_AND_REC_END					39
#define	EDIT_ACTION_PLAY_AND_REC_FILE_PLAY_START		40
#define	EDIT_ACTION_PLAY_AND_REC_FILE_PLAY_END			41
#define	EDIT_ACTION_PLAY_AND_REC_FILE_OVERWRITE_START	42
#define	EDIT_ACTION_PLAY_AND_REC_FILE_OVERWRITE_END		43
#define	EDIT_ACTION_SD_SAVE_STRART						44
#define	EDIT_ACTION_SD_SAVE_END							45
#define	EDIT_ACTION_KEY_POSITION_START					46
#define	EDIT_ACTION_KEY_POSITION_END					47
#define	EDIT_ACTION_NON_INIT_PLAY_START					48
#define	EDIT_ACTION_PLAY_END_STOP						49


typedef enum{
	VIDEO_STATUS_NORMAL = 0,
	VIDEO_STATUS_REC,
	VIDEO_STATUS_PLAY,
	VIDEO_STATUS_REPEAT_PLAY,
	VIDEO_STATUS_MOTION1_REC,
	VIDEO_STATUS_MOTION1_PLAY,
	VIDEO_STATUS_MOTION2_REC,
	VIDEO_STATUS_MOTION2_PLAY,
	VIDEO_STATUS_MOTION3_REC,
	VIDEO_STATUS_MOTION3_PLAY,
	VIDEO_STATUS_MOTION4_REC,
	VIDEO_STATUS_MOTION4_PLAY,
	VIDEO_STATUS_MOTION5_REC,
	VIDEO_STATUS_MOTION5_PLAY,
	VIDEO_STATUS_MOTION6_REC,
	VIDEO_STATUS_MOTION6_PLAY,
	VIDEO_STATUS_MOTION7_REC,
	VIDEO_STATUS_MOTION7_PLAY,
	VIDEO_STATUS_MOTION8_REC,
	VIDEO_STATUS_MOTION8_PLAY,
	VIDEO_STATUS_PLAY_AND_REC,
	VIDEO_STATUS_PLAY_AND_REC_PLAY,
	VIDEO_STATUS_REPEAT_PLAY2,
	VIDEO_STATUS_PLAY_END_STOP
}video_status_enum_t;

typedef struct{
	uint8_t 	action;
	uint32_t	option_value;
}prtc_data_ctl_edit_action_t;

typedef struct{
	uint8_t 	action;
	uint32_t	option_value;
}prtc_data_rsp_edit_action_t;

typedef struct{
	uint8_t 	status;
}prtc_data_ctl_edit_status_t;

typedef struct{
	uint8_t 	status;
}prtc_data_rsp_edit_status_t;

///////////////////////////action///////////////////////////

/***********************************************************EDIT_SUB_PID_ACTION**********************************************************/
#pragma pack()
#endif